=== Noxxxxious/Rubiks-website/rubiks/xml+xsd/rubik.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="componentType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="content" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:byte"/>
    </xs:complexType>

    <xs:complexType name="descriptionType">
        <xs:sequence>
            <xs:element name="component" type="componentType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="source">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="title" type="xs:string"/>
                        <xs:element ref="link"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="about" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="linkType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="src" type="xs:anyURI" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

    <xs:element name="link" type="linkType"/>

    <xs:complexType name="methodType" mixed="true">
        <xs:sequence>
            <xs:element name="method_name" type="xs:string"/>
            <xs:element ref="link"/>
        </xs:sequence>
        <xs:attribute ref="diff" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="methodsType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="method" type="methodType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:attribute name="diff" type="diffType" />
	<xs:simpleType name="diffType" >
		<xs:restriction base="xs:token" >
			<xs:enumeration value="begginer" />
			<xs:enumeration value="advanced" />
			<xs:enumeration value="pro" />
		</xs:restriction>
	</xs:simpleType>

    <xs:complexType name="puzzlesType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element ref="cube" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="cube" type="linkType"/>

    <xs:simpleType name="timeType">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0.01"/>
            <xs:maxInclusive value="10.00"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="longstring">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="50"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="date">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1976"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tournamentType">
        <xs:union memberTypes="longstring date"/>
    </xs:simpleType>

    <xs:complexType name="recordType">
        <xs:sequence>
            <xs:element name="time" type="timeType"/>
            <xs:element name="date" type="xs:date"/>
            <xs:element name="tournament" type="tournamentType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="shortstringType">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="20"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ageType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="120"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="medalsType">
        <xs:list>
            <xs:simpleType>
                <xs:restriction base="xs:string">
                    <xs:maxLength value="11"/>
                </xs:restriction>
            </xs:simpleType>
        </xs:list>
    </xs:simpleType>

    <xs:group name="cuberdata">
        <xs:sequence>
            <xs:element name="fname" type="shortstringType"/>
            <xs:element name="surname" type="shortstringType"/>
            <xs:element name="age" type="ageType"/>
            <xs:element name="nationality" type="shortstringType"/>
            <xs:element name="record" type="recordType"/>
            <xs:element name="medals" type="medalsType"/>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="speedcubersType">
        <xs:sequence>
            <xs:element name="title" type="xs:string"/>
            <xs:element name="speedcuber" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:group ref="cuberdata"/>
                    <xs:attribute name="gender" use="optional"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="authorType" mixed="true">
        <xs:sequence>
            <xs:element name="fname" type="shortstringType"/>
            <xs:element name="surname" type="shortstringType"/>
            <xs:element name="faculty">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[W]([A-Z])*"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="index">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="[1-9][0-9][0-9][0-9][0-9][0-9]"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
        <xs:attribute ref="gender" use="optional"/>
        <xs:attribute name="nationality" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="([a-zA-Z])*[@]([a-zA-Z])*[.]([a-zA-Z])*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:attribute name="gender">
        <xs:simpleType>
            <xs:restriction base="xs:string">
                <xs:pattern value="male|female|other"/>
            </xs:restriction>
        </xs:simpleType> 
    </xs:attribute>

    <xs:element name="rubik">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description" type="descriptionType"/>
                <xs:element name="methods" type="methodsType"/>
                <xs:element name="puzzles" type="puzzlesType"/>
                <xs:element name="speedcubers" type="speedcubersType"/>
                <xs:element name="author" type="authorType"/>
                <xs:element name="contact">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="tel" type="xs:decimal"/>
                            <xs:element name="email" type="emailType"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Noxxxxious/Rubiks-website/rubiks/xml+xsd/rubik.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="rubik.xslt"?>
<rubik xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="rubik.xsd">
    <description about="Kostki Rubika">
        <component id="1">
            <title>Czym jest Kostka Rubika?</title>
            <content>
                Kostka Rubika jest zabawką logiczną wynalezioną przez Ernő Rubika w 1974 roku. W 1976 roku została skonstruowana i opatentowana w Japonii przez inżyniera Terutoshiego Ishige.
            </content>
        </component>
        <component id="2">
            <title>Ilość Kombinacji</title>
            <content>
                Kostka Rubika posiada 6 ścian, a każda z nich sklada się z 9 kolorowych kwadratów. Taka konfiguracja pozwala na ponad 43 tryliony różnych ułożeń.  
            </content>
        </component>
        <component id="3">
            <title>Optymalne rozwiązanie</title>
            <content>
                W 2010 zespół matematyków za pomocą serwerów Google udowodnił, że ‘boską’ liczbą dla kostki Rubika jest 20. Oznacza to, że każde ułożenie można rozwiązać maksymalnie w 20 ruchach.
            </content>
        </component>
        <source>
            <title>Źródło</title>
            <link src="https://pl.wikipedia.org/wiki/Kostka_Rubika#Oficjalne_rekordy_World_Cube_Association">Wikipedia</link>
        </source>
    </description>

    <methods>
        <title>Metody układania kostki</title>
        <method diff="begginer">
            <method_name>LBL (Layer by Layer)</method_name>
            <link src="https://pl.wikipedia.org/wiki/Layer_by_Layer">meotda dla początkujących</link>
        </method>
        <method diff="advanced">
            <method_name>Metoda Fridrich (tzw. CFOP)</method_name>
            <link src="https://pl.wikipedia.org/wiki/Metoda_Fridrich">metoda zaawansowana</link>
        </method>
        <method diff="pro">
            <method_name>Metoda Petrusa</method_name>
            <link src="https://pl.wikipedia.org/wiki/Metoda_Petrusa">technika jak najmniejszej ilości ruchów</link>
        </method>
    </methods>

    <puzzles>
        <title>Galeria Kostek</title>
        <cube src="img/1/cube2.jpg">2x2</cube>
        <cube src="img/1/cube3.jpg">3x3</cube>
        <cube src="img/1/cube4.jpg">4x4</cube>
        <cube src="img/1/cube5.jpg">5x5</cube>
        <cube src="img/1/cube10.jpg">10x10</cube>
        <cube src="img/1/pyraminx.jpg">Pyraminx</cube>
        <cube src="img/1/megaminx.jpg">Megaminx</cube>
        <cube src="img/1/skewb.jpg">Skewb</cube>
        <cube src="img/2/cube339.jpg">3x3x9</cube>
        <cube src="img/2/gear.jpg">Gear Cube</cube>
        <cube src="img/3/square1.jpg">Square-1</cube>
        <cube src="img/3/mirror3.jpg">Mirror Cube</cube>
        <cube src="img/2/wheel.jpg">Wheel of time Cube</cube>
    </puzzles>

    <speedcubers>
        <title>Najlepsi speedcuberzy</title>
        <speedcuber gender="male">
            <fname>Yusheng</fname>
            <surname>Du</surname>
            <age>17</age>
            <nationality>Chiny</nationality>
            <record>
                <time>3.47</time>
                <date>2018-11-24</date>
                <tournament>Wuhu Open 2018</tournament>
            </record>
            <medals>złote-71 srebrne-49 brązowe-33</medals>
        </speedcuber>
        <speedcuber gender="male">
            <fname>Feliks</fname>
            <surname>Zemdegs</surname>
            <age>24</age>
            <nationality>Australia</nationality>
            <record>
                <time>4.16</time>
                <date>2020-02-29</date>
                <tournament>Auckland Summer Open 2020</tournament>
            </record>
            <medals>złote-606 srebrne-109 brązowe-59</medals>
        </speedcuber>
        <speedcuber gender="male">
            <fname>Patrick</fname>
            <surname>Ponce</surname>
            <age>20</age>
            <nationality>Stany Zjednoczone</nationality>
            <record>
                <time>4.24</time>
                <date>2019-02-17</date>
                <tournament>Northeast Championship 2019</tournament>
            </record>
            <medals>złote-152 srebrne-64 brązowe-37</medals>
        </speedcuber>
    </speedcubers>

    <author gender="male" nationality="Poland">
        <fname>Michał</fname>
        <surname>Wrzosek</surname>
        <faculty>WETI</faculty>
        <index>184608</index>
    </author>

    <contact>
        <tel>321654987</tel>
        <email>adres@web.com</email>
    </contact>

</rubik>
